export const SMS_ACTIVATE_TO_5SIM: Record<string, string> = {
    'wa': 'whatsapp',
    'go': 'google',
    'tg': 'telegram',
    'fb': 'facebook',
    'ig': 'instagram',
    'tw': 'twitter',
    'ds': 'discord',
    'vi': 'viber',
    'lf': 'tiktok',
    'fu': 'snapchat',
    'wb': 'wechat',
    'vk': 'vkontakte',
    'ok': 'odnoklassniki',
    'ma': 'mail.ru',
    'me': 'line',
    'mm': 'microsoft',
    'mb': 'yahoo',
    'am': 'amazon',
    'nf': 'netflix',
    'st': 'steam',
    'pl': 'paypal',
    'ub': 'uber',
    'ot': 'other',
    'hw': 'alibaba',
    'dr': 'openai',
    'ts': 'paypal', // duplicate check
    'gr': 'grindr',
    'mt': 'steam',
    'blm': 'blizzard',
    'bz': 'blizzard',
    'mo': 'bumble',
    'oi': 'tinder',
    'qv': 'badoo',
    'vz': 'hinge',
    'alj': 'spotify',
    'hb': 'twitch',
    'yt': 'youtube',
    'tn': 'linkedIn',
    'li': 'linkedin',
    'ew': 'nike',
    'av': 'avito',
    'kl': 'kakaotalk',
    'dh': 'ebay',
    'dp': 'deliveroo',
    'uk': 'airbnb',
    'pz': 'lalamove',
    'pm': 'aol',
    'ft': 'grab',
    'bd': 'bolt',
    'kp': 'hq trivia',
    'dt': 'delivery club',
    'ya': 'yandex',
    'ym': 'yandex',
}

export const get5simProductName = (smsActivateCode: string): string => {
    return SMS_ACTIVATE_TO_5SIM[smsActivateCode.toLowerCase()] || smsActivateCode.toLowerCase();
}
