#!/bin/bash

echo "🔍 Vérification des logs de la fonction receive-email"
echo ""
echo "Va sur ce lien pour voir les logs en temps réel:"
echo "https://supabase.com/dashboard/project/htfqmamvmhdoixqcbbbw/functions/receive-email/logs"
echo ""
echo "📧 Maintenant:"
echo "1. Envoie un email simple à support@onesms-sn.com"
echo "2. Attends 10 secondes"
echo "3. Regarde les logs Supabase"
echo ""
echo "Cherche dans les logs:"
echo "  - 'Available fields:' → voir quels champs le webhook envoie"
echo "  - 'Email details retrieved' → voir si l'API retourne des données"
echo "  - 'Message text found:' → voir le contenu récupéré"
echo ""
echo "Ensuite vérifie dans la DB avec:"
echo "  node deep_analyse_email_content.mjs"
