#!/bin/bash

# 🚀 PLAN COMPLET DE MIGRATION SUPABASE CLOUD → COOLIFY
# Date: 8 décembre 2025

echo "🚀 MIGRATION SUPABASE CLOUD → COOLIFY"
echo "======================================"
echo ""

# STATUT ACTUEL
echo "✅ DÉJÀ FAIT:"
echo "   - ✅ Base de données exportée (194,763 lignes)"
echo "   - ✅ Données importées: 22,696 lignes"
echo "   - ✅ Schéma complet créé (30 tables)"
echo "   - ✅ Clés API Coolify récupérées"
echo ""

# CE QUI RESTE
echo "⚠️  À FAIRE:"
echo ""
echo "1️⃣  COMPLÉTER L'IMPORT DES DONNÉES (172,067 lignes manquantes)"
echo "   - balance_operations: 264 lignes manquantes"
echo "   - rental_logs: 62,450 lignes manquantes"
echo "   - pricing_rules_archive: 109,353 lignes manquantes"
echo "   📝 Script: node import_remaining_data.mjs"
echo ""

echo "2️⃣  MIGRATIONS SQL (34 migrations)"
echo "   - Appliquer toutes les migrations du dossier supabase/migrations/"
echo "   - Vérifier que les fonctions SQL sont créées"
echo "   📝 Commandes:"
echo "      ssh root@46.202.171.108"
echo "      cd /path/to/migrations"
echo "      docker exec -i supabase-db-h888cc0ck4w4o0kgw4kg84ks psql -U postgres -d postgres < migration.sql"
echo ""

echo "3️⃣  EDGE FUNCTIONS (61 fonctions)"
echo "   📦 Catégories:"
echo "      - Paiements: 9 fonctions (PayDunya, MoneyFusion, Moneroo, PayTech)"
echo "      - SMS/Activations: 25 fonctions (SMS Activate, 5SIM)"
echo "      - Services: 8 fonctions (sync, countries)"
echo "      - Cron: 4 fonctions (atomic, pending-sms, wallet-health)"
echo "      - Webhooks: inclus dans paiements"
echo "      - Autres: 15 fonctions"
echo ""
echo "   📝 Déploiement:"
echo "      # 1. Configurer Supabase CLI pour Coolify"
echo "      supabase link --project-ref default"
echo "      # URL: http://supabasekong-h888cc0ck4w4o0kgw4kg84ks.46.202.171.108.sslip.io"
echo ""
echo "      # 2. Déployer toutes les fonctions"
echo "      cd supabase/functions"
echo "      supabase functions deploy --all"
echo ""

echo "4️⃣  SECRETS & ENVIRONNEMENT (27 variables)"
echo "   📝 À configurer dans Coolify:"
echo "      - APIs SMS Activate"
echo "      - Clés PayTech, Moneroo, MoneyFusion, PayDunya"
echo "      - Firebase (push notifications)"
echo "      - AWS (si utilisé)"
echo "      - URLs de callbacks/webhooks"
echo ""

echo "5️⃣  CRON JOBS (3 tâches planifiées)"
echo "   - cron-atomic-reliable"
echo "   - cron-check-pending-sms"
echo "   - cron-wallet-health"
echo ""
echo "   📝 Configuration dans Coolify ou via pg_cron"
echo ""

echo "6️⃣  AUTH & UTILISATEURS (64 utilisateurs)"
echo "   ✅ Déjà importés"
echo "   ⚠️  Vérifier:"
echo "      - Email confirmation settings"
echo "      - SMTP configuration"
echo "      - Sessions actives"
echo ""

echo "7️⃣  STORAGE / BUCKETS"
echo "   ℹ️  Aucun bucket trouvé (ou non accessible via API)"
echo "   📝 Si des fichiers existent, utiliser:"
echo "      supabase storage download-all"
echo "      # Puis uploader vers Coolify"
echo ""

echo "8️⃣  WEBHOOKS EXTERNES"
echo "   ⚠️  Mettre à jour les URLs dans:"
echo "      - PayDunya dashboard → http://coolify.../paydunya-webhook"
echo "      - MoneyFusion dashboard → http://coolify.../moneyfusion-webhook"
echo "      - Moneroo dashboard → http://coolify.../moneroo-webhook"
echo "      - PayTech dashboard → http://coolify.../paytech-ipn"
echo "      - SMS Activate → http://coolify.../webhook-sms-activate"
echo ""

echo "9️⃣  FRONTEND & CONFIGURATION"
echo "   📝 Commandes:"
echo "      # 1. Basculer vers .env.coolify"
echo "      cp .env .env.backup"
echo "      cp .env.coolify .env"
echo ""
echo "      # 2. Tester en local"
echo "      npm run dev"
echo ""
echo "      # 3. Build & déployer"
echo "      npm run build"
echo "      netlify deploy --prod"
echo ""

echo "🔟  TESTS & VALIDATION"
echo "   📝 Checklist:"
echo "      [ ] Login/Signup fonctionne"
echo "      [ ] Liste des services charge"
echo "      [ ] Achat d'activation fonctionne"
echo "      [ ] Paiement PayDunya fonctionne"
echo "      [ ] SMS reçus correctement"
echo "      [ ] Wallet balance correct"
echo "      [ ] Admin panel accessible"
echo "      [ ] Webhooks reçus et traités"
echo ""

echo "======================================"
echo "🎯 PROCHAINE ÉTAPE IMMÉDIATE:"
echo "   1. Importer les données manquantes (172K lignes)"
echo "   2. Déployer les Edge Functions"
echo "   3. Configurer les secrets"
echo ""
echo "Veux-tu commencer par l'import des données manquantes ? (Y/n)"
